### ISSUE TITLE
Add password reset functionality

### ISSUE THREAD

**Issue by c-marion** [AppDevOrganization/5A6-group-project#22]
**Task Description**
The user should be able to reset their password if they happened to forget it

**Steps**
- [x] Add a reset password button to the login page.
- [x] Create reset password page
- [x] Make it send a password reset email
- [x] Confirm the password reset
- [x] Ask the user to type a new password?
