### ISSUE TITLE
Create chequing, savings, and credit screens

### ISSUE THREAD

**Issue by c-marion** [AppDevOrganization/5A6-group-project#26]
**Requirement Description**
The user should be able to see and interact with their chequing

### Tasks
- [x] [Chequing and Savings Accounts](https://github.com/AppDevOrganization/5A6-group-project/issues/27)
- [x] [Transaction list in chequing and savings](https://github.com/AppDevOrganization/5A6-group-project/issues/29)
- [x] [Total Money display in savings and chequing](https://github.com/AppDevOrganization/5A6-group-project/issues/28)
- [x] [Transaction list in credit](https://github.com/AppDevOrganization/5A6-group-project/issues/49)
- [x] [Credit screen](https://github.com/AppDevOrganization/5A6-group-project/issues/24)
