### ISSUE TITLE
Credit Account

### ISSUE THREAD

**Issue by jco898** [AppDevOrganization/5A6-group-project#47]
**Requirement Description**
Creating a Credit Account screen that displays the statement balance & due date, a list of transactions, and a pay bill button that navigates to the transfer screen.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

```[tasklist]
### Tasks
- [ ] Displaying the statement balance & due date in the Credit Account screen
- [ ] Adding transactions to the Credit Account screen
- [ ] Adding a pay bill button to Credit Account screen
```

**Effort estimation (LOE)**
8

**Additional context**
Add any other context about the requirement here.
